name: Java CICD With Github Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-docker-image-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: maven build
      run: mvn clean install

    - name: configure aws ecr
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}

    - name: login to aws ecr
      id: login-pf-aws-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: build and push docker image
      env:
        ECR_REGISTRY: ${{secrets.AWS_ECR_REGISTRY}} #${{steps.login-pf-aws-ecr.output.registry}}
        ECR_REPOSITORY: ${{secrets.REPO_NAME}}
        IMAGE_TAG: ${{github.sha}}

      run: | 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:IMAGE_TAG
      
