name: Deploy Lambda Function

on:
  push:
    branches:
      - master
#    paths:
#      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install zip tool
        uses: montudor/action-zip@v1
      - name: create zip file for lambda function
        run: cd src && zip -r lambda.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
              --function-name arn:aws:lambda:ap-south-1:565544423927:function:CICD_Demo \
              --zip-file fileb://src/lambda.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: "ap-south-1"



